### PR TITLE
Fix build against vtk greater 9.1 and itk with custom namespace

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
See https://github.com/Slicer/Slicer/issues/6587

**Comment by lassoan** [comment]
@jcfr we switched back to using the Slicer fork - see https://github.com/acil-bwh/ChestImagingPlatform/pull/45.

So, you may consider closing this PR here and submit to https://github.com/Slicer/ChestImagingPlatform/ instead.

**Comment by acil-bwh** [comment]
> @jcfr we switched back to using the Slicer fork - see #45.
> 
> So, you may consider closing this PR here and submit to https://github.com/Slicer/ChestImagingPlatform/ instead.

Sorry for doing this. I can integrate back the changes on the fork after you are done so we don't block your PRs

**Comment by acil-bwh** [comment]
PR has been moved to a Slicer fork

**Comment by lassoan** [comment]
If you are not comfortable with us making changes directly in this repository then using two repositories is the way to go. This allows us to immediately act on urgent issues and then whenever you have time you can fetch updates from our repository.

**Comment by rjosest** [comment]
Hi Andras,

That sounds like a plan. I’m totally conformable with you making changes directly into the repo. But we can follow with fetches from the fork. Happy to hear your thoughts about the best way to do that once you are done with the compatibility changes

Thanks

**Comment by jcfr** [comment]
Thanks @rjosest , it is great that we can now more easily update the upstream projects 🙏👌

Thanks @lassoan for integrating the change on the Slicer fork, I will finalize the update shortly to ensure we can build the project.

**Pull request closed without merging**
